# More info on Hadolint: Hadolint: https://github.com/hadolint/hadolint
# More info: https://confluence.lmera.ericsson.se/display/ACD/Hadolint

no-fail: false # Make true to always return code 0; indicating process success; irrespective of the rule violations and failure-threshold
no-color: false # Make true to disable colorized output
format: json #Options [tty|json|checkstyle|codeclimate|gitlab_codeclimate|codacy]

# List of registries to pull images from
trustedRegistries:
  - armdocker.rnd.ericsson.se

# List of Rules to be Ignored.
ignored:
  - DL3049 # https://github.com/hadolint/hadolint/wiki/DL3049#label-label-is-missing
  - DL3037 # https://github.com/hadolint/hadolint/wiki/DL3037#specify-version-with-zypper-install--y-packageversion
  - DL3050 # https://github.com/hadolint/hadolint/wiki/DL3050#superfluous-labels-present

# Override the severity of a rule. For example, some violations that are only thrown as warnings, you can upgrade to errors
override:
  error:
    - DL3001 # https://github.com/hadolint/hadolint/wiki/DL3001#command-does-not-make-sense-in-a-container
    - DL3002 # https://github.com/hadolint/hadolint/wiki/DL3002#last-user-should-not-be-root
  warning:
    - DL3042 # https://github.com/hadolint/hadolint/wiki/DL3042#avoid-cache-directory-with-pip-install---no-cache-dir-package
    - DL3033 # https://github.com/hadolint/hadolint/wiki/DL3033#specify-version-with-yum-install--y-package-version
  info:
    - DL3032 # https://github.com/hadolint/hadolint/wiki/DL3032#yum-clean-all-missing-after-yum-command
  style:
    - DL3015 # https://github.com/hadolint/hadolint/wiki/DL3015#avoid-additional-packages-by-specifying---no-install-recommends

# Expected labels in the Dockerfile
label-schema:
  author: text
  version: semver
strict-labels: true # Warns of additional labels outside the schema. Make false to disable the warning.

# Exit with code 1; indicating process failure; when rules with severity equal to or above threshold are violated. Options [error|warning|info|style|ignore|none]
failure-threshold: error
