import:
  common: bob-properties.yaml

model_version: 2.0
product_va_config:
  name: "${common.helm-chart-name}"
  product_name: "${common.helm-chart-name}"
  version: {version}
  va_template_version: 2.0.0
  description: IDUN Microservice chassis with Bob based CI and release automation pipelines
  images:
    - /${helmChartName}:{version}
  mitigations:
    CVE-2015-8855:
      mitigation: This is a placeholder, example mitigation. Add mitigation steps below.
      sce:
        sce-id: SCE-1234-00
        status: Pending
        expires: 2022-12-10T00:00:00Z
